package frc.robot.subsystems;

import com.ctre.phoenix.ErrorCode;
import com.ctre.phoenix.led.CANdle;
import com.ctre.phoenix.led.CANdleConfiguration;
import com.ctre.phoenix.led.CANdleFaults;
import com.ctre.phoenix.led.StrobeAnimation;
import com.ctre.phoenix.led.CANdle.LEDStripType;

import edu.wpi.first.wpilibj2.command.SubsystemBase;


public class TwoLEDSubsytem extends SubsystemBase {
   
   private CANdle mGPCANdle;
   private CANdleConfiguration mGPConfig;
   private StrobeAnimation mStrobeAnimation;


   public TwoLEDSubsytem(){
    
    mGPCANdle = new CANdle(1);

    mGPConfig = new CANdleConfiguration();
    mGPConfig.stripType = LEDStripType.RGB;
    mGPConfig.brightnessScalar = 1.0;
    mGPCANdle.configAllSettings(mGPConfig);

   

    ErrorCode error = mGPCANdle.getLastError(); // gets the last error generated by the CANdle
    CANdleFaults faults = new CANdleFaults();
    ErrorCode faultsError = mGPCANdle.getFaults(faults); // fills faults with the current CANdle faults; returns the last error generated


    }


    public void setConeLED(){

        mGPCANdle.setLEDs(255, 129, 3, 0, 1, 12); //Cone LED
        
    }

    public void setCubeLED(){

        mGPCANdle.setLEDs(154,  3, 255, 0, 13, 12); //Cube LED


    }

    public void setConeAnim(){

        mStrobeAnimation = new StrobeAnimation(255, 129, 3, 0, 1, 12, 1);
        
    }

    public void setCubeAnim(){

        mStrobeAnimation = new StrobeAnimation(255, 129, 3, 0, 1, 12, 13);

    }



}
